version: '3'
services:
    library-laravel-demo:
        container_name: library-laravel-demo
        build:
            context: ./docker
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - library-laravel-demo-network
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0.32'
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
            MYSQL_DATABASE: "libraryLaravelDemo"
        ports:
            - 3306:3306
        volumes:
            - ./storage/db:/var/lib/mysql
        networks:
            - library-laravel-demo-network
networks:
    library-laravel-demo-network:
        driver: bridge
